EXPERIMENT:
  NAME: ""
  TAG: "r032_a99"
  PROJECT: "sner-hptune"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  SUBSET: True
  INPUT_SIZE: [224, 224]
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "AMD_SNER_v3"
  TEACHER: "vit_large"
  STUDENT: "vit_tiny"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 1.0E-4
  SGD:
    MOMENTUM: 0.9
  SCHEDULE: 
    MULTISTEP:
      STAGES: [30, 60, 90]
      RATE: 0.1
  WEIGHT_DECAY: 0.0001
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
AMD:
  M_LAYERS: [11, 17]
  ALIGN_TYPE: 'mse'
  LOSS:
    FEAT_WEIGHT: 1.0
    ORTHO_WEIGHT: 1.0
    NULLSPACE_WEIGHT: 1.0
  SNER:
    RANK: 32
    NULL_THRES: 0.05
    OUTLIER_Q: 0.99
    METHOD: 'sner'

